import canon from '../data/canon.json'
const aliases = [
	{ id: 'gen', name: 'Genesis', aliases: ['gen', 'ge', 'gn'] },
	{ id: 'exo', name: 'Exodus', aliases: ['exod', 'exo', 'ex'] },
	{ id: 'lev', name: 'Leviticus', aliases: ['lev', 'lv'] },
	{ id: 'num', name: 'Numbers', aliases: ['num', 'numb', 'nu', 'nm'] },
	{ id: 'deu', name: 'Deuteronomy', aliases: ['deut', 'deu', 'dt'] },
	{ id: 'jos', name: 'Joshua', aliases: ['josh', 'jos'] },
	{ id: 'jdg', name: 'Judges', aliases: ['judg', 'jdg', 'jg'] },
	{ id: 'rut', name: 'Ruth', aliases: ['ruth', 'rut', 'ru', 'rth'] },
	{
		id: '1sa',
		name: '1 Samuel',
		aliases: [
			'1samuel',
			'1sam',
			'1sa',
			'1sm',
			'firstsamuel',
			'firstsam',
			'isamuel',
			'isam',
		],
	},
	{
		id: '2sa',
		name: '2 Samuel',
		aliases: [
			'2samuel',
			'2sam',
			'2sa',
			'2sm',
			'secondsamuel',
			'secondsam',
			'iisamuel',
			'iisam',
		],
	},
	{
		id: '1ki',
		name: '1 Kings',
		aliases: [
			'1kings',
			'1kgs',
			'1ki',
			'1kg',
			'firstkings',
			'firstkgs',
			'ikings',
			'ikgs',
		],
	},
	{
		id: '2ki',
		name: '2 Kings',
		aliases: [
			'2kings',
			'2kgs',
			'2ki',
			'2kg',
			'secondkings',
			'secondkgs',
			'iikings',
			'iikgs',
		],
	},
	{
		id: '1ch',
		name: '1 Chronicles',
		aliases: [
			'1chronicles',
			'1chron',
			'1chr',
			'1ch',
			'firstchronicles',
			'firstchron',
			'ichronicles',
			'ichron',
		],
	},
	{
		id: '2ch',
		name: '2 Chronicles',
		aliases: [
			'2chronicles',
			'2chron',
			'2chr',
			'2ch',
			'secondchronicles',
			'secondchron',
			'iichronicles',
			'iichron',
		],
	},
	{ id: 'ezr', name: 'Ezra', aliases: ['ezra', 'ezr'] },
	{ id: 'neh', name: 'Nehemiah', aliases: ['neh', 'ne'] },
	{ id: 'est', name: 'Esther', aliases: ['esther', 'esth', 'est'] },
	{ id: 'job', name: 'Job', aliases: ['job'] },
	{
		id: 'psa',
		name: 'Psalm',
		aliases: ['psalm', 'psalms', 'psa', 'ps', 'pss'],
	},
	{ id: 'pro', name: 'Proverbs', aliases: ['proverbs', 'prov', 'pro', 'prv'] },
	{
		id: 'ecc',
		name: 'Ecclesiastes',
		aliases: ['ecclesiastes', 'eccl', 'ecc', 'qoheleth'],
	},
	{
		id: 'sng',
		name: 'Song of Solomon',
		aliases: [
			'songofsolomon',
			'songofsongs',
			'song',
			'sos',
			'sng',
			'canticles',
		],
	},
	{ id: 'isa', name: 'Isaiah', aliases: ['isaiah', 'isa', 'is'] },
	{ id: 'jer', name: 'Jeremiah', aliases: ['jeremiah', 'jer'] },
	{ id: 'lam', name: 'Lamentations', aliases: ['lamentations', 'lam'] },
	{ id: 'ezk', name: 'Ezekiel', aliases: ['ezekiel', 'ezek', 'ezk', 'eze'] },
	{ id: 'dan', name: 'Daniel', aliases: ['daniel', 'dan', 'dn'] },
	{ id: 'hos', name: 'Hosea', aliases: ['hosea', 'hos'] },
	{ id: 'jol', name: 'Joel', aliases: ['joel', 'jol', 'joe'] },
	{ id: 'amo', name: 'Amos', aliases: ['amos', 'amo', 'am'] },
	{ id: 'oba', name: 'Obadiah', aliases: ['obadiah', 'obad', 'oba'] },
	{ id: 'jon', name: 'Jonah', aliases: ['jonah', 'jon'] },
	{ id: 'mic', name: 'Micah', aliases: ['micah', 'mic'] },
	{ id: 'nam', name: 'Nahum', aliases: ['nahum', 'nah', 'nam'] },
	{ id: 'hab', name: 'Habakkuk', aliases: ['habakkuk', 'hab'] },
	{ id: 'zep', name: 'Zephaniah', aliases: ['zephaniah', 'zeph', 'zep'] },
	{ id: 'hag', name: 'Haggai', aliases: ['haggai', 'hag'] },
	{ id: 'zec', name: 'Zechariah', aliases: ['zechariah', 'zech', 'zec'] },
	{ id: 'mal', name: 'Malachi', aliases: ['malachi', 'mal'] },
	{ id: 'mat', name: 'Matthew', aliases: ['matthew', 'matt', 'mat', 'mt'] },
	{ id: 'mrk', name: 'Mark', aliases: ['mark', 'mrk', 'mk', 'mar'] },
	{ id: 'luk', name: 'Luke', aliases: ['luke', 'luk', 'lk'] },
	{ id: 'jhn', name: 'John', aliases: ['john', 'jhn', 'jn'] },
	{ id: 'act', name: 'Acts', aliases: ['acts', 'act', 'ac'] },
	{ id: 'rom', name: 'Romans', aliases: ['romans', 'rom', 'ro'] },
	{
		id: '1co',
		name: '1 Corinthians',
		aliases: [
			'1corinthians',
			'1cor',
			'1co',
			'firstcorinthians',
			'firstcor',
			'icorinthians',
			'icor',
		],
	},
	{
		id: '2co',
		name: '2 Corinthians',
		aliases: [
			'2corinthians',
			'2cor',
			'2co',
			'secondcorinthians',
			'secondcor',
			'iicorinthians',
			'iicor',
		],
	},
	{ id: 'gal', name: 'Galatians', aliases: ['galatians', 'gal'] },
	{ id: 'eph', name: 'Ephesians', aliases: ['ephesians', 'eph'] },
	{
		id: 'php',
		name: 'Philippians',
		aliases: ['philippians', 'php', 'phil', 'pp'],
	},
	{ id: 'col', name: 'Colossians', aliases: ['colossians', 'col'] },
	{
		id: '1th',
		name: '1 Thessalonians',
		aliases: [
			'1thessalonians',
			'1thess',
			'1th',
			'firstthessalonians',
			'firstthess',
			'ithessalonians',
			'ithess',
		],
	},
	{
		id: '2th',
		name: '2 Thessalonians',
		aliases: [
			'2thessalonians',
			'2thess',
			'2th',
			'secondthessalonians',
			'secondthess',
			'iithessalonians',
			'iithess',
		],
	},
	{
		id: '1ti',
		name: '1 Timothy',
		aliases: [
			'1timothy',
			'1tim',
			'1ti',
			'firsttimothy',
			'firsttim',
			'itimothy',
			'itim',
		],
	},
	{
		id: '2ti',
		name: '2 Timothy',
		aliases: [
			'2timothy',
			'2tim',
			'2ti',
			'secondtimothy',
			'secondtim',
			'iitimothy',
			'iitim',
		],
	},
	{ id: 'tit', name: 'Titus', aliases: ['titus', 'tit'] },
	{ id: 'phm', name: 'Philemon', aliases: ['philemon', 'phm', 'phlm'] },
	{ id: 'heb', name: 'Hebrews', aliases: ['hebrews', 'heb'] },
	{ id: 'jas', name: 'James', aliases: ['james', 'jas', 'jam'] },
	{
		id: '1pe',
		name: '1 Peter',
		aliases: [
			'1peter',
			'1pet',
			'1pe',
			'firstpeter',
			'firstpet',
			'ipeter',
			'ipet',
		],
	},
	{
		id: '2pe',
		name: '2 Peter',
		aliases: [
			'2peter',
			'2pet',
			'2pe',
			'secondpeter',
			'secondpet',
			'iipeter',
			'iipet',
		],
	},
	{
		id: '1jn',
		name: '1 John',
		aliases: ['1john', '1jhn', '1jn', 'firstjohn', 'firstjn', 'ijohn', 'ijn'],
	},
	{
		id: '2jn',
		name: '2 John',
		aliases: [
			'2john',
			'2jhn',
			'2jn',
			'secondjohn',
			'secondjn',
			'iijohn',
			'iijn',
		],
	},
	{
		id: '3jn',
		name: '3 John',
		aliases: [
			'3john',
			'3jhn',
			'3jn',
			'thirdjohn',
			'thirdjn',
			'iiijohn',
			'iiijn',
		],
	},
	{ id: 'jud', name: 'Jude', aliases: ['jude', 'jud'] },
	{ id: 'rev', name: 'Revelation', aliases: ['revelation', 'rev', 're'] },
]

export const books = canon.map((book) => ({
	...book,
	name: book.id === 'sng' ? 'Song of Solomon' : book.name,
	aliases: aliases.find((a) => a.id === book.id)!.aliases,
}))
export const bookById = (id: string) => books.find((book) => book.id === id)
const key = (name: string) => name.toLowerCase().replace(/[^a-z0-9]/g, '')
export function findBook(name: string) {
	const query = key(name)
	if (!query) return undefined
	const exact = books.filter((b) =>
		[b.name, b.id, ...b.aliases].some((a) => key(a) === query),
	)
	if (exact.length) return exact.length === 1 ? exact[0] : undefined
	const partial = books.filter((b) =>
		[b.name, ...b.aliases].some((a) => key(a).startsWith(query)),
	)
	return partial.length === 1 ? partial[0] : undefined
}
export const chapterIndex = books.flatMap((b) =>
	b.verses.map((_, i) => ({ book: b.id, chapter: i + 1 })),
)
export const chapterNumber = (book: string, chapter: number) =>
	chapterIndex.findIndex((c) => c.book === book && c.chapter === chapter)
