import { test, expect } from '@playwright/test'
import { jump, settled, verseTop } from '../e2e/helpers'
import { mockDownload } from '../e2e/download-fixture'

test('direct Pages links preserve ranges, history, assets and offline reading', async ({ page, context, isMobile }) => {
	const failures: string[] = []
	page.on('response', (r) => {
		if (!r.ok() && r.request().resourceType() !== 'document') failures.push(r.url())
	})
	const response = await page.goto('/instant-bible/John/3/16,18-19?version=BSB')
	expect(response?.status()).toBe(404)
	await settled(page)
	await expect(page.locator('[data-verse="jhn.3.16"]')).toHaveClass(/indicated/)
	await expect(page.locator('[data-verse="jhn.3.18"]')).toHaveClass(/indicated/)
	await expect.poll(async () => Math.round(await verseTop(page, 'jhn.3.16'))).toBe(isMobile ? 24 : 48)
	await expect(page).toHaveURL(/\/instant-bible\/John\/3\/16,18-19\?version=BSB$/)
	const manifest = await page.evaluate(async () => fetch('/instant-bible/manifest.webmanifest').then((r) => r.json()))
	expect(manifest.start_url).toBe('/instant-bible/')
	expect(manifest.scope).toBe('/instant-bible/')
	expect(manifest.icons.every((i: { src: string }) => i.src.startsWith('/instant-bible/'))).toBe(true)
	await page.evaluate(() => navigator.serviceWorker.ready.then((r) => r.scope))
	await page.reload()
	await settled(page)
	await expect.poll(() => page.evaluate(() => navigator.serviceWorker.controller?.scriptURL)).toBe('http://127.0.0.1:4174/instant-bible/sw.js')
	await jump(page, 'Romans8:28')
	await expect(page).toHaveURL(/\/instant-bible\/Romans\/8\/28\?version=BSB$/)
	await page.goBack()
	await expect(page.getByRole('button', { name: 'Open reference picker' })).toHaveText('John 3')
	await page.goForward()
	await expect(page.getByRole('button', { name: 'Open reference picker' })).toHaveText('Romans 8')
	await context.setOffline(true)
	await jump(page, 'Psalm119:176')
	await expect(page.locator('[data-verse="psa.119.176"]').first()).toContainText('I have strayed like a lost sheep')
	await page.reload()
	await settled(page)
	await expect(page).toHaveURL(/\/instant-bible\/Psalm\/119\/176\?version=BSB$/)
	await expect(page.locator('[data-verse="psa.119.176"]').first()).toContainText('I have strayed like a lost sheep')
	expect(failures).toEqual([])
})

test('root launch, optional installs, selection links and offline restarts use the deployment base', async ({ page, context }) => {
	await mockDownload(page)
	await page.goto('/instant-bible/')
	await settled(page)
	await expect(page).toHaveURL(/\/instant-bible\/Genesis\/1\?version=BSB$/)
	await page.evaluate(() => navigator.serviceWorker.ready.then(() => {}))
	await page.reload()
	await settled(page)
	await page.getByRole('button', { name: 'Open reference picker' }).click()
	await page.getByRole('button', { name: 'Choose translation' }).click()
	await page.getByRole('button', { name: 'Use World English Bible', exact: true }).click()
	await expect(page.getByRole('button', { name: 'Choose translation' })).toHaveText('WEB', { timeout: 15000 })
	await page.getByRole('textbox', { name: 'Bible reference' }).fill('John21:25;Acts1:1-2')
	await page.getByRole('textbox', { name: 'Bible reference' }).press('Enter')
	await expect(page).toHaveURL(/\/instant-bible\/John\/21\/25\?version=WEB&selection=/)
	expect(await page.evaluate(async () => {
		const cache = await caches.open('bible-data-v1-eng_web')
		return (await cache.keys()).map((r) => new URL(r.url).pathname)
	})).toEqual(expect.arrayContaining(['/instant-bible/bibles/v1/WEB/metadata.json', '/instant-bible/bibles/v1/WEB/act.json']))
	await context.setOffline(true)
	await page.reload()
	await settled(page)
	await expect(page.locator('[data-verse="jhn.21.25"]').first()).toHaveClass(/indicated/)
	await expect(page.locator('[data-verse="act.1.1"]').first()).toHaveClass(/indicated/)
	await jump(page, 'Jude5')
	await expect(page).toHaveURL(/\/instant-bible\/Jude\/1\/5\?version=WEB$/)
})
